spring.application.name=product-service
server.port=8200
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.service.defaultZone=http://localhost:8761/eureka
spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
file.upload-dir=C:/myapp/uploads
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
